### ISSUE TITLE
Deploy a Sonarqube service

### ISSUE THREAD

**Issue by calebespinoza** [BC-LT-AT-FS-04/ConfigManage#5]
As an operator, I need to provide a service to run static code analysis and show reports to developers about the state of the code in the repos MLService and ConverterService. SonarQube Community Edition is the solution we need to accomplish with this requirement.

**Acceptance Criteria:**
* SonarQube service should be available in this URL: https://sonarqube.at04.devops.jala.university
* The official image of SonarQube should use to deploy it from this repository in Docker hub: https://hub.docker.com/_/sonarqube
* The port 9000/tcp should be exposed in the server for SonarQube.
* SonarQube should be deployed in the server via Ansible

**Dependency:**
* This item depends on https://github.com/BC-LT-AT-FS-04/ConfigManage/issues/1

**Supporting docs:**
- https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html
- https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_v2_module.html

**Comment by calebespinoza** [comment]
Please @RhemJos and @Artmo10 attach the PR to this working item.

**Comment by RhemJos** [comment]
We reviewed the observations. To complete the task we had two approaches, one of them has been sent in the PR, in which to deploy both SonarQube and PostgreSQL we use only the `deploy_sonarqube.yml` file. 
An initial approach was followed to deploy both SonarQube and PostgreSQL using the Ansible `community.docker.docker_compose_v2` module to manage the deployment directly from a Docker Compose file named `sonarqube.yml`. To deploy using this method, it is important to copy the `sonarqube.yml` file to the development server. We found this [info](https://stackoverflow.com/questions/62452039/how-to-run-docker-compose-commands-with-ansible) that highlights the importance of copying the file. To follow this approach we suggest to organize the repository by creating a directory named `compose_files` to host this file (`sonarqube.yml`) and any other Docker Compose files that may be needed in the future. 

### 💡 Tasks to deploy SonarQube

The following tasks are required:
1. **Ensure the target directory for the Docker Compose file exists.**  
2. **Copy the `sonarqube.yml` file to the server.**  
3. **Start SonarQube using the `docker_compose_v2` module.**

Following is the content for the `deploy_sonarqube.yml` file in case of implementing this approach:

```yaml
---
- name: Ensure target directory for Docker Compose file exists
  ansible.builtin.file:
    path: /opt/sonarqube
    state: directory
    mode: '0755'

- name: Copy Docker Compose file to development server
  ansible.builtin.copy:
    src: compose_files/sonarqube.yml
    dest: /opt/sonarqube/sonarqube.yml
    mode: '0644'

- name: Start SonarQube
  community.docker.docker_compose_v2:
    project_src: /opt/sonarqube
    files:
      - /opt/sonarqube/sonarqube.yml
    state: present
```

### 📂 Suggested File Organization
The following structure is suggested for organizing files, with a **new directory**, **new file** and **edited files**:

```
.
├── .github/workflows
├── compose_files/  # 🟢 New directory
│   └── sonarqube.yml  # 🟢 New file
├── group_vars/
│   └── vars.yml
├── host_vars/
│   ├── inventory.ini
│   └── inventory.yml
├── tasks/
│   ├── deploy_docker.yml
│   └── deploy_sonarqube.yml  # 🟢 Edited
├── .ansible-lint-ignore
├── .gitignore
└── playbook.yml  # 🟢 Edited
```


### 📄 Docker Compose File
Following is the content for the `sonarqube.yml` file in case of implementing this approach:

```yaml

services:
    sonarqube:
        image: sonarqube:10.7.0-community
        container_name: sonarqube
        ports:
            - 9000:9000
        environment:
            SONAR_JDBC_URL: jdbc:postgresql://db/sonardb
            SONAR_JDBC_USERNAME: sonar
            SONAR_JDBC_PASSWORD: root
        volumes:
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_extensions:/opt/sonarqube/extensions
            - sonarqube_logs:/opt/sonarqube/logs
        networks:
            - sonarnet

    db:
        image: postgres:13.18
        container_name: db-server
        environment:
            POSTGRES_USER: sonar
            POSTGRES_PASSWORD: root
            POSTGRES_DB: sonardb
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - sonarnet
 
networks:
    sonarnet:

volumes:
    sonarqube_data:
    sonarqube_extensions:
    sonarqube_logs:
    pgdata:

```

@calebespinoza, we would appreciate your feedback on which of the approaches considered would be most appropriate following good practices.
